---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      name: mongo
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      initContainers:
        - name: init-mongo
          image: alpine
          command: ['/bin/sh']
          args: ['-c', 'mkdir -p /mnt/db && chmod -R 777 /mnt/db']
          volumeMounts:
          - mountPath: /mnt
            name: data-vol
            readOnly: false
      containers:
        - name: mongo
          image: docker.io/mongo
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - mountPath: /data
              name: data-vol
              readOnly: false
      volumes:
        - name: data-vol
          emptyDir: {}
